### ISSUE TITLE
recontribute to Vim

### ISSUE THREAD

**Issue by Konfekt** [lbrayner/vim-rzip#11]
Ola, Have you considered informing the maintainer of `:e $VIMRUNTIME/plugin/zipPlugin.vim` about your plug-in? Perhaps these enhancements could go into it.

**Comment by lbrayner** [comment]
Hi! I think maybe subconsciuosly I thought he would be as receptive as Braam or the netrw manintainer (whose name I forgot). I'll consider it, thanks.

**Comment by Konfekt** [comment]
In fact, it is the `netrw` maintainer. Worth a try, in any event. O não é garantido, dizem.

**Comment by lbrayner** [comment]
Haha, even tpope couldn't ge through to him! But I'll at least try. Obrigado!
