### ISSUE TITLE
[Feature Request] Support for unlimited zip/jar Chain

### ISSUE THREAD

**Issue by sihunqu123** [lbrayner/vim-rzip#18]
Consider `myConfig.properties` is in d.jar
, which is in c.zip
, which is in b.zip
, which is in a.zip
(the overall structure is `a.zip/b.zip/c.zip/d.jar/myConfig.properties`)

Could you help to also support cases like this(unlimited zip/jar chain), thanks.

**Comment by lbrayner** [comment]
Hey, did you have any issues trying to edit such a file? It's supposed to work, and I just tested it.

**Comment by lbrayner** [comment]
[![asciicast](https://asciinema.org/a/531651.svg)](https://asciinema.org/a/531651)
