### ISSUE TITLE
error messages in opening a zip archive within a zip archive

### ISSUE THREAD

**Issue by boryeumao** [lbrayner/vim-rzip#19]
I am getting the following messages:

  Error detected while processing function <SNR>25_ZipBrowseSelect:                                                                    
  line   25:
  E117: Unknown function: rzip#util#escapeFileName
  line   26:
  E121: Undefined variable: zipname
  E116: Invalid arguments for function insert

The second level archive seems to have been opened OK, so these messages weren't fatal, but I would like to sort them out - any hint on which of the script files to look for the source of the messages?  Thanks.

Debian 11.  VIM 8.2  

PS - Since my machine is not connected, the script files are unzipped from the vim-rzip-master.zip, and not 'git cloned' as directed in the README file.

**Comment by lbrayner** [comment]
Hi, @boryeumao ! Is it possible to attach the zip file?

**Comment by lbrayner** [comment]
Here's the same demo run on VIM - Vi IMproved 8.2.2434, the current version on Debian bullseye.

[![asciicast](https://asciinema.org/a/4vJQ0sIya2IA1iISN4I4IT9aC.svg)](https://asciinema.org/a/4vJQ0sIya2IA1iISN4I4IT9aC)

**Comment by boryeumao** [comment]
Yes. Here is a simple zip file: a smaill text file 'test' is zipped to t1.zip, which is then zipped to t2.zip. Both t2.zip and t1.zip are opened OK, but the errors show up when opening test.

Thank you.


     On Tuesday, February 14, 2023, 03:41:49 AM PST, Leonardo ***@***.***> wrote:  
 
 


Hi, @boryeumao ! Is it possible to attach the zip file?

**Comment by boryeumao** [comment]
Ah thaks for the demo. Opening file with ':e <file>' works without errors. Only when I tried opening <file> by placing the cursor on the file name and hitting <enter>.


     On Tuesday, February 14, 2023, 06:30:13 AM PST, Leonardo ***@***.***> wrote:  
 
 


Here's the same demo run on VIM - Vi IMproved 8.2.2434, the current version on Debian bullseye.

**Comment by boryeumao** [comment]
Some test results:

vi t2.zip - cursor-open t1.zip - cursor-open test -------> errors
vi t2.zip - ':e1 t1.zip' - ':e1 test' ----------------------------> no errors
vi t2.zip - ':e1 t1.zip' - cursor-open test -------------------> no errors

     On Tuesday, February 14, 2023, 08:33:59 AM PST, Boryeu Mao ***@***.***> wrote:  
 
  Ah thaks for the demo. Opening file with ':e <file>' works without errors. Only when I tried opening <file> by placing the cursor on the file name and hitting <enter>.


     On Tuesday, February 14, 2023, 06:30:13 AM PST, Leonardo ***@***.***> wrote:  
 
 


Here's the same demo run on VIM - Vi IMproved 8.2.2434, the current version on Debian bullseye.

**Comment by lbrayner** [comment]
@boryeumao you did not attach the t1.zip file. You have to attach it here on Github, I don't think it works if you reply via email.

**Comment by lbrayner** [comment]
By the way, `:e test` does not trigger vim-rzip, only `zipfile://` URLs or files ending in `.zip`.

**Comment by boryeumao** [comment]
My apologies.... here it is


     On Tuesday, February 14, 2023, 09:01:47 AM PST, Leonardo ***@***.***> wrote:  
 
 


@boryeumao you did not attach the t1.zip file. You have to attach it here on Github, I don't think it works if you reply via email.

**Comment by boryeumao** [comment]
Sorry - I misunderstood the demo you'd sent.


     On Tuesday, February 14, 2023, 09:04:22 AM PST, Leonardo ***@***.***> wrote:  
 
 


By the way, :e test does not trigger vim-rzip, only zipfile:// URLs or files ending in .zip.

**Comment by boryeumao** [comment]
So in the case of t2.zip, the errors occur upon opening the 3rd level file, which happens to be a regular text file in this example, but same errors too with a (3rd level) zip archive. Could the errors come from outside vim-rzip? (although the error messages do contain name/function references therein). I've debugged some vim (rather simple) scripts that I wrote myself, but without a good picture of vim-rzip I feel somewhat powerless here :(


     On Tuesday, February 14, 2023, 11:10:49 AM PST, Boryeu Mao ***@***.***> wrote:  
 
  Sorry - I misunderstood the demo you'd sent.


     On Tuesday, February 14, 2023, 09:04:22 AM PST, Leonardo ***@***.***> wrote:  
 
 


By the way, :e test does not trigger vim-rzip, only zipfile:// URLs or files ending in .zip.

**Comment by lbrayner** [comment]
@boryeumao you still did not attach the zip file you're having trouble with. You have to come to https://github.com/lbrayner/vim-rzip/issues/19, create a new comment and attach the file. Attaching it via email will not work.

**Comment by boryeumao** [comment]
[t2.zip](https://github.com/lbrayner/vim-rzip/files/10736155/t2.zip)

Hopefully this does it....

**Comment by boryeumao** [comment]
Looks like this may be where the errros came from:

Browsing zipfile zipfile:///home/user/w/n_s/n/qubes/R4.1.1/t2.zip::t1.zip

**Comment by lbrayner** [comment]
@boryeumao Here's a demo showing how to install the plugin manually using Vim packages and with your file in the same folder hierarchy:

[![asciicast](https://asciinema.org/a/wmUmuxL9MWEIpwyRNTUCNwI0F.svg)](https://asciinema.org/a/wmUmuxL9MWEIpwyRNTUCNwI0F)

No errors.

**Comment by boryeumao** [comment]
Got it -- my manual installation had everything under start/, missing the vim-rzip/ directory.  I have averted plugins so far, hence the lack of understanding of a 'package'-level directory.  Big lesson for me - Thank you so much, for the help and for vim-rzip.

**Comment by boryeumao** [comment]
If it is OK I will close the issue.

**Comment by lbrayner** [comment]
@boryeumao  I'm glad you sorted it ou!
